/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocalidad;

import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class Formulario extends javax.swing.JFrame {

    public Formulario() {
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("../FOTOS/logo3.png")).getImage());
        jusuario.setVisible(false);
        Textoregistrado.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        Jugar.setVisible(false);
         usuarionull.setVisible(false);
        Usuario.setNextFocusableComponent(Password);
        Password.setNextFocusableComponent(inciarSesion);
        UsuarioNuevo.setNextFocusableComponent(PassNuevo);
        PassNuevo.setNextFocusableComponent(bRegistrar);
        inciarSesion.setNextFocusableComponent(Usuario);
        bRegistrar.setNextFocusableComponent(UsuarioNuevo);
    }

    public void registrar() throws Exception {
        ConexionOracle con = new ConexionOracle();
        con.Conexion();

        Statement stm = con.getConexion().createStatement();

        ResultSet rs = stm.executeQuery("SELECT id FROM USUARIO WHERE id='" + UsuarioNuevo.getText() + "'");

        boolean Stock = false;
        String nombre = "";
        if (rs.next()) {
            jusuario.setVisible(true);
        } else {
            stm.executeUpdate("INSERT INTO USUARIO (id, password,PUNTOSPACMAN,PUNTOSPAR,PUNTOSTETRIS) VALUES('" + UsuarioNuevo.getText() + "','" + PassNuevo.getText() + "'," + 0 + "," + 0 + "," + 0 + ")");
            Textoregistrado.setVisible(true);
            Jugar.setVisible(true);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
                        jLabel6.setVisible(false);
            jLabel5.setVisible(false);
            jLabel4.setVisible(false);
            jLabel3.setVisible(false);
            jLabel2.setVisible(false);
            jLabel1.setVisible(false);
            Usuario.setVisible(false);
            Password.setVisible(false);
            UsuarioNuevo.setVisible(false);
            PassNuevo.setVisible(false);
            jSeparator1.setVisible(false);
            jSeparator2.setVisible(false);
            jSeparator3.setVisible(false);            
            jSeparator4.setVisible(false);
            jSeparator5.setVisible(false);
            jSeparator6.setVisible(false);
            jSeparator7.setVisible(false);
            jSeparator8.setVisible(false);            
            inciarSesion.setVisible(false);
            bRegistrar.setVisible(false);
            usuarionull.setVisible(false);
        }
        stm.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuarionull = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsuarioNuevo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PassNuevo = new javax.swing.JTextField();
        bRegistrar = new javax.swing.JButton();
        jusuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        inciarSesion = new javax.swing.JButton();
        Textoregistrado = new javax.swing.JLabel();
        Jugar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(660, 440));
        setPreferredSize(new java.awt.Dimension(660, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("USUARIO*:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        usuarionull.setFont(new java.awt.Font("ZapfHumnst Dm BT", 1, 18)); // NOI18N
        usuarionull.setForeground(new java.awt.Color(255, 0, 51));
        usuarionull.setText("(*) CAMPOS OBLIGATORIOS");
        getContentPane().add(usuarionull, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 270, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setText("DATE DE ALTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        UsuarioNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        UsuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(UsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD*:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));
        getContentPane().add(PassNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 140, -1));

        bRegistrar.setBackground(new java.awt.Color(255, 0, 0));
        bRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        bRegistrar.setText("Registrar");
        bRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bRegistrar.setBorderPainted(false);
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 90, 30));

        jusuario.setFont(new java.awt.Font("ZapfHumnst Dm BT", 1, 18)); // NOI18N
        jusuario.setForeground(new java.awt.Color(255, 0, 51));
        jusuario.setText("YA EXISTE USUARIO");
        getContentPane().add(jusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 240, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("USUARIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("PASSWORD:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setText("INICIAR SESION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsuarioFocusLost(evt);
            }
        });
        Usuario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                UsuarioInputMethodTextChanged(evt);
            }
        });
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 140, -1));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, -1));

        inciarSesion.setBackground(new java.awt.Color(255, 0, 0));
        inciarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        inciarSesion.setText("Acceder");
        inciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inciarSesion.setBorderPainted(false);
        inciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(inciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, 30));

        Textoregistrado.setFont(new java.awt.Font("ZapfHumnst Dm BT", 1, 36)); // NOI18N
        Textoregistrado.setForeground(new java.awt.Color(0, 204, 102));
        Textoregistrado.setText("Bienvenido. Juega ya a PlayUHU.");
        getContentPane().add(Textoregistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 50));

        Jugar.setBackground(new java.awt.Color(0, 102, 0));
        Jugar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jugar.setForeground(new java.awt.Color(255, 255, 255));
        Jugar.setText("JUGAR");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, 40));

        jLabel7.setFont(new java.awt.Font("ZapfHumnst Dm BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("USUARIO O CONTRASEÑA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 260, -1));

        jLabel8.setFont(new java.awt.Font("ZapfHumnst Dm BT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("INCORRECTOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 20, 140));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 210, 130));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, 10));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 20, 140));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 20, 140));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 210, 130));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 210, 130));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 20, 140));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTOS/logo3_t.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 420, 160));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTOS/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -40, 920, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoActionPerformed

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed

        try {
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
             usuarionull.setVisible(false);
             jusuario.setVisible(false);
            if(UsuarioNuevo.getText().length()>0 && PassNuevo.getText().length()>0){
            registrar();
            }else{
                
                usuarionull.setVisible(true);
            }

        } catch (Exception ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void inciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inciarSesionActionPerformed
        jusuario.setVisible(false);
        ConexionOracle con = new ConexionOracle();
        con.Conexion();
        Statement stm;
        try {
            stm = con.getConexion().createStatement();

            ResultSet rs = stm.executeQuery("SELECT id FROM USUARIO WHERE id='" + Usuario.getText() + "' AND password='" + Password.getText() + "'");

            if (rs.next()) {

                new Inicio(this).setVisible(true);
                this.setVisible(false);
                usuarionull.setVisible(false);
            }
            else
            {
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
               
            }

        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_inciarSesionActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        try {
            new Inicio(this).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_JugarActionPerformed

    private void UsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioFocusLost
        // TODO add your handling code here:
        Password.setFocusable(true);
    }//GEN-LAST:event_UsuarioFocusLost

    private void UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_UsuarioKeyPressed

    private void UsuarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_UsuarioInputMethodTextChanged
        // TODO add your handling code here:
        Password.setFocusable(true);
    }//GEN-LAST:event_UsuarioInputMethodTextChanged

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    String nombreUsuario() {
        return Usuario.getText();
    }

    String nombreNuevo() {
        return UsuarioNuevo.getText();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugar;
    private javax.swing.JTextField PassNuevo;
    private javax.swing.JTextField Password;
    private javax.swing.JLabel Textoregistrado;
    private javax.swing.JTextField Usuario;
    private javax.swing.JTextField UsuarioNuevo;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JButton inciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jusuario;
    private javax.swing.JLabel usuarionull;
    // End of variables declaration//GEN-END:variables
}
